---

- name: "Remove apt package {{ __flameshot_package }} or it will break version checking."
  apt:
    name: "{{ __flameshot_package }}"
    state: "absent"

- name: "Gather installed apt packages in search for Snap."
  package_facts:
    manager: apt

- name: "Remove snap package {{ __flameshot_package }} or it will break version checking."
  snap:
    name: "{{ __flameshot_package }}"
    state: "absent"
  when: >
    'snapd' in ansible_facts.packages
