---
- name: Install prezto from git.
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: "{{ lookup('env','HOME') }}/.zprezto/"
    track_submodules: true
    force: true
    update: false

# - name: Install prezto dotfiles.
#   file:
#     src: "{{ item }}"
#     dest: "{{ lookup('env','HOME') }}/.{{ item | basename }}"
#     state: link
#   with_fileglob: "{{ lookup('env','HOME') }}/.zprezto/runcoms/*"
#   when: item|basename != "README.md"

- name: Install prezto theme from git.
  git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "{{ lookup('env','HOME')}}/.zprezto/modules/prompt/external/powerlevel10k"
    force: true

- name: Link prezto theme.
  file:
    src: "{{ lookup('env','HOME')}}/.zprezto/modules/prompt/external/powerlevel10k/powerlevel10k.zsh-theme"
    dest: "{{ lookup('env','HOME')}}/.zprezto/modules/prompt/functions/prompt_powerlevel10k_setup"
    state: link
    force: true

- name: change user shell to zsh
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh
  become: true