---

- hosts: localhost
  user: pedro
  connection: local

  vars:
    - is_home_laptop: true

  vars_files:
    - vars/main.yml


  tasks:
    - include_tasks: 
        file: tasks/zsh.yml

    - include_tasks: 
        file: tasks/dotfiles.yml