---

- hosts: localhost
  user: pedro
  connection: local
  become: yes

  vars:
      - is_home_laptop: true

  vars_files:
    - vars/main.yml

  roles:
    - role: geerlingguy.dotfiles
    - role: baztian.calibre
    - role: joplin
      users:
        - username: pedro
          settings:
            - { key: "sidebarVisibility", val: "1" }
            - { key: "dateFormat", val: "YYYY-MM-DD" }
            - { key: "sync.target", val: "5" }

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600
    
    
  tasks:
    - name: Remove broken Ubuntu PPA for Ansible (not working on focal)
      apt_repository:
        repo: "ppa:ansible/ansible"
        state: absent      
        update_cache: yes
   
    - name: Add GPG key for Sublime Text
      apt_key:
          url: "https://download.sublimetext.com/sublimehq-pub.gpg"
          state: present

    - name: Add APT repository for Sublime Text
      apt_repository:
          filename: sublime-text.list
          repo: deb https://download.sublimetext.com/ apt/stable/
          update_cache: yes

    - name: Add required PPA repositories
      apt_repository: 
          repo: "{{item}}" 
          update_cache: yes
      with_items: "{{ppas}}"

    #- name: Update APT repository
    #  apt:
    #      update_cache: yes # todo only if above changed?

    - name: Install apt packages
      apt:
          name: "{{ apt_installed_packages }}"
          state: present

    - name: Install img2pdf
      pip:
          name: img2pdf

    - name: Install Youtube-DL
      pip:
          name: youtube_dl

    - name: Install jrnl
      pip:
         name: jrnl

    - name: Install prezto from git.
      git:
          repo: https://github.com/sorin-ionescu/prezto.git
          dest: "{{ lookup('env','HOME') }}/.zprezto/"
          track_submodules: true
          force: true
          update: false

    - name: Install prezto dotfiles.
      file:
          src: "{{ item }}"
          dest: "{{ lookup('env','HOME') }}/.{{ item | basename }}"
          state: link
      with_fileglob: "{{ lookup('env','HOME') }}/.zprezto/runcoms/*"
      when: item|basename != "README.md"

    - name: Install prezto theme from git.
      git:
          repo: "https://github.com/romkatv/powerlevel10k.git"
          dest: "{{ lookup('env','HOME')}}/.zprezto/modules/prompt/external/powerlevel10k"
          force: true

    - name: Link prezto theme.
      file:
          src: "{{ lookup('env','HOME')}}/.zprezto/modules/prompt/external/powerlevel10k/powerlevel10k.zsh-theme"
          dest: "{{ lookup('env','HOME')}}/.zprezto/modules/prompt/functions/prompt_powerlevel10k_setup"
          state: link
          force: true		

# TODO: mullvad, chsh, dropbox, rbenv