---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  # - name: centos6
  #   image: centos:6
  - name: centos7
    image: centos:7
  - name: fedora27
    image: fedora:27
  - name: fedora28
    image: fedora:28
  - name: fedora29
    image: fedora:29
  # - name: fedora30
  #   image: fedora:30
  # - name: ubuntu14
  #   image: ubuntu:14.04
  - name: ubuntu16
    image: ubuntu:16.04
  - name: ubuntu18
    image: ubuntu:18.04
  - name: debian8
    image: debian:8
  - name: debian9
    image: debian:9
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
